### ISSUE TITLE
How rest authentication works?

### ISSUE THREAD

**Issue by binuraj-rs** [pac4j/spring-security-pac4j-demo#11]
Hi,

 I am reffering your spring-security-pac4j-demo project for uri protection. Let me know one thing How can I access a page through rest.
 My scenario is here,
 
 1. I have a page "rest/RestView.jsp" which is protected with spring security.
	
		<security:http pattern="/rest/**" entry-point-ref="casWrapperEntryPoint">
			<security:csrf disabled="true"/>
			<security:intercept-url pattern="/rest/**" access="isAuthenticated()" />
        </security:http>
		
 2. Configured the casWrapperEntryPoint and casWrapperClient,
 
	<bean id="casWrapperEntryPoint" class="org.pac4j.springframework.security.web.ClientAuthenticationEntryPoint">
        <property name="client" ref="casWrapperClient" />
    </bean>
    
    <bean id="casWrapperClient" class="org.pac4j.oauth.client.CasOAuthWrapperClient">
        <property name="key" value="this_is_the_key" />
        <property name="secret" value="this_is_the_secret" />
        <property name="casOAuthUrl" value="http://localhost:8080/cas2/oauth2.0" />
    </bean>
	
	
 The process is worked whwn I test with browser. Now I want to check with rest client. For that I follow these steps,
 
 1. Generate authentication ticket through rest client,
 
	http://localhost:8080/cas2/v1/tickets?username=jleleu&password=jleleu
	
 2. Generate service ticket for acessing the rest,
 
	http://localhost:8080/cas2/v1/tickets/TGT-9-J7WAgHUfjjL36l51pffiaCbRd4nSpehzVs5KQDW4WNLuo5CYHL-cas01.example.org
	
 3. Accessing the rest,
 
	http://localhost:9999/rest/RestView.jsp?ticket=ST-12-OJ2cCHjZm3FEL41cNsw5-cas01.example.org.

But here the response is the code of cas login page. Is there any Token authenticatior I missed? Please check and letme know your comments

**Comment by leleuj** [comment]
Will reply on the pac4j-users mailing lists: https://groups.google.com/forum/?fromgroups#!topic/pac4j-users/YVA5Yt7v700
