### ISSUE TITLE
login with office 365

### ISSUE THREAD

**Issue by Gil9091e10** [pac4j/spring-security-pac4j-demo#19]
How could I implement an authentication mechanism but with office 365? I recently had the need to implement security for my rest service but through office 365 accounts

Thanks

**Comment by leleuj** [comment]
If we are to add a new authentication mechanism, it must happen in the pac4j security engine: https://github.com/pac4j/pac4j

Please open a discussion on the pac4j-dev mailing list if you need some help in this contribution.
