### ISSUE TITLE
Upgrade to Spring Security 4

### ISSUE THREAD

**Issue by JacobASeverson** [pac4j/spring-security-pac4j-demo#7]
Upgrading some versions and schemas in anticipation of the upgrades in the spring-security-pac4j project.

**Comment by JacobASeverson** [comment]
PR https://github.com/pac4j/spring-security-pac4j-demo/pull/6

**Comment by leleuj** [comment]
Thanks

**Comment by leleuj** [comment]
@JacobASeverson : FYI, some additional updates to make everything work: https://github.com/pac4j/spring-security-pac4j-demo/pull/8

**Comment by JacobASeverson** [comment]
Ah looks good- I didn't do full testing on the sample app so these updates make sense.

**Comment by leleuj** [comment]
Still a work in progress, especially on the logout filter side (which matches only POST requests on "/logout" by default)...

**Comment by leleuj** [comment]
I just released spring-security-pac4j v1.3.0, it will be available in the Maven central repository in a few hours. I'll make a few announcements here and there.

Based on pac4j v1.8, we'll be able to provide a better implementation for the credentials erasure.
If you want to get more involved and tackle the pac4j upgrade more generally, ping me

**Comment by JacobASeverson** [comment]
:+1: Great stuff!
